# --8<-- [start:quickstart-imports]
import asyncio

from group_terminal.server import ChatServer

# --8<-- [end:quickstart-imports]


# --8<-- [start:quickstart-chatapp]
class ChatApp:
    def __init__(self, host: str, port: int):
        self._server = ChatServer(host=host, port=port)
        self._server.add_handler(self._handle_message)

    @property
    def server(self):
        return self._server

    async def _process_message(self, content: str, username: str):
        # potentially long-running operation ...
        response = f"I received '{content}' from {username}"
        # send response to chat clients
        await self._server.send_message(response, sender="agent", agent=True)

    async def _handle_message(self, content: str, username: str):
        # Handles messages generated by chat clients i.e. users. A
        # handler is called sequentially in message arrival order.
        # This is the same order as seen in the chat client.

        # Operations that require preserving message arrival order
        # (adding to a queue, ...) should be done here. Long-running
        # message processing should be done asynchronously to prevent
        # blocking the message receiver loop.
        asyncio.create_task(self._process_message(content, username))


# --8<-- [end:quickstart-chatapp]


async def main():
    # --8<-- [start:quickstart-main]
    app = ChatApp(host="0.0.0.0", port=8723)
    await app.server.start()
    await app.server.join()


# --8<-- [end:quickstart-main]


if __name__ == "__main__":
    asyncio.run(main())
